### ISSUE TITLE
from llama import Llama ModuleNotFoundError: No module named 'llama'

### ISSUE THREAD

**Issue by pkoli437** [meta-llama/llama#1039]
I tried running this code while loading the model : 
`` !torchrun --nproc_per_node 1 /content/example_text_completion.py --ckpt_dir /content/drive/MyDrive/Llama 2/llama-2-13b `-tokenizer_path` /content/drive/MyDrive/Llama 2/tokenizer.model --max_seq_len 128 --max_batch_size 6
``
`` Traceback (most recent call last):
  File "/content/example_text_completion.py", line 6, in <module>
    from llama import Llama
ModuleNotFoundError: No module named 'llama'
[2024-02-26 11:53:49,569] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2661) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/content/example_text_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-26_11:53:49
  host      : f9202a2d804c
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2661)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
`` 
Getting this error even when tried : 
pip install llama-cpp-python
pip install llama==0.1.1 and various other. 

 Any Solutiton ?

**Comment by skard17** [comment]
I meet the same bug.Could you tell me how you solved it?
