### ISSUE TITLE
cannot find pytorch_model-00001-of-00003.bin

### ISSUE THREAD

**Issue by Hannan1002** [meta-llama/llama#1073]
Got error while running the vicuna model using start_windows.bat:
Traceback (most recent call last):

File "C:\Users\hanna\Downloads\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\modeling_utils.py", line 530, in load_state_dict

return torch.load(

       ^^^^^^^^^^^
File "C:\Users\hanna\Downloads\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\serialization.py", line 998, in load

with _open_file_like(f, 'rb') as opened_file:

     ^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\hanna\Downloads\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\serialization.py", line 445, in _open_file_like

return _open_file(name_or_buffer, mode)

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\hanna\Downloads\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\serialization.py", line 426, in init

super().__init__(open(name, mode))

                 ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'models\vicuna-13b-GPTQ-4bit-128g\pytorch_model-00001-of-00003.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "C:\Users\hanna\Downloads\text-generation-webui-main\text-generation-webui-main\modules\ui_model_menu.py", line 245, in load_model_wrapper

shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\hanna\Downloads\text-generation-webui-main\text-generation-webui-main\modules\models.py", line 87, in load_model

output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\hanna\Downloads\text-generation-webui-main\text-generation-webui-main\modules\models.py", line 153, in huggingface_loader

model = LoaderClass.from_pretrained(path_to_model, **params)

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\hanna\Downloads\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\models\auto\auto_factory.py", line 561, in from_pretrained

return model_class.from_pretrained(

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\hanna\Downloads\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\modeling_utils.py", line 3502, in from_pretrained

) = cls._load_pretrained_model(

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\hanna\Downloads\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\modeling_utils.py", line 3903, in _load_pretrained_model

state_dict = load_state_dict(shard_file)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\hanna\Downloads\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\transformers\modeling_utils.py", line 538, in load_state_dict

with open(checkpoint_file) as f:

     ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'models\vicuna-13b-GPTQ-4bit-128g\pytorch_model-00001-of-00003.bin'

**Comment by WuhanMonkey** [comment]
Hi @Hannan1002, seems like you are using this [repo]([text-generation-webui](https://github.com/oobabooga/text-generation-webui))?  Please post this question on their issues. But I think you need to download the model artifacts first (mostly gonna be from huggingface)
