### ISSUE TITLE
Test Tokenizer gives Incorrect padding error

### ISSUE THREAD

**Issue by dinuransika** [meta-llama/llama#1119]
## Describe the bug
Downloaded the `Meta-Llama-3-8B` model using the given download script. Then when I tried to use the tokenizer model with the given `llama/test_tokenizer.py` file it gives the following error. 

### Minimal reproducible example
```
TOKENIZER_PATH=llama3/Meta-Llama-3-8B/tokenizer.model python3 -m unittest llama/test_tokenizer.py
```

### Output

```
EEEEE
======================================================================
ERROR: test_decode (llama.test_tokenizer.TokenizerTests.test_decode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fahad/dinura/llama3/llama/test_tokenizer.py", line 12, in setUp
    self.tokenizer = Tokenizer(os.environ["TOKENIZER_PATH"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/dinura/llama3/llama/tokenizer.py", line 58, in __init__
    mergeable_ranks = load_tiktoken_bpe(model_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/site-packages/tiktoken/load.py", line 148, in load_tiktoken_bpe
    return {
           ^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/site-packages/tiktoken/load.py", line 149, in <dictcomp>
    base64.b64decode(token): int(rank)
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding

======================================================================
ERROR: test_encode (llama.test_tokenizer.TokenizerTests.test_encode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fahad/dinura/llama3/llama/test_tokenizer.py", line 12, in setUp
    self.tokenizer = Tokenizer(os.environ["TOKENIZER_PATH"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/dinura/llama3/llama/tokenizer.py", line 58, in __init__
    mergeable_ranks = load_tiktoken_bpe(model_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/site-packages/tiktoken/load.py", line 148, in load_tiktoken_bpe
    return {
           ^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/site-packages/tiktoken/load.py", line 149, in <dictcomp>
    base64.b64decode(token): int(rank)
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding

======================================================================
ERROR: test_encode_dialog (llama.test_tokenizer.TokenizerTests.test_encode_dialog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fahad/dinura/llama3/llama/test_tokenizer.py", line 12, in setUp
    self.tokenizer = Tokenizer(os.environ["TOKENIZER_PATH"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/dinura/llama3/llama/tokenizer.py", line 58, in __init__
    mergeable_ranks = load_tiktoken_bpe(model_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/site-packages/tiktoken/load.py", line 148, in load_tiktoken_bpe
    return {
           ^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/site-packages/tiktoken/load.py", line 149, in <dictcomp>
    base64.b64decode(token): int(rank)
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding

======================================================================
ERROR: test_encode_message (llama.test_tokenizer.TokenizerTests.test_encode_message)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fahad/dinura/llama3/llama/test_tokenizer.py", line 12, in setUp
    self.tokenizer = Tokenizer(os.environ["TOKENIZER_PATH"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/dinura/llama3/llama/tokenizer.py", line 58, in __init__
    mergeable_ranks = load_tiktoken_bpe(model_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/site-packages/tiktoken/load.py", line 148, in load_tiktoken_bpe
    return {
           ^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/site-packages/tiktoken/load.py", line 149, in <dictcomp>
    base64.b64decode(token): int(rank)
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding

======================================================================
ERROR: test_special_tokens (llama.test_tokenizer.TokenizerTests.test_special_tokens)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fahad/dinura/llama3/llama/test_tokenizer.py", line 12, in setUp
    self.tokenizer = Tokenizer(os.environ["TOKENIZER_PATH"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/dinura/llama3/llama/tokenizer.py", line 58, in __init__
    mergeable_ranks = load_tiktoken_bpe(model_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/site-packages/tiktoken/load.py", line 148, in load_tiktoken_bpe
    return {
           ^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/site-packages/tiktoken/load.py", line 149, in <dictcomp>
    base64.b64decode(token): int(rank)
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fahad/anaconda3/envs/dinllm/lib/python3.11/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)
```

## Runtime Environment
- Model: [`Meta-Llama-3-8B`]
- Using via huggingface?: [no]
- OS: [Linux]
- GPU VRAM: 47.99GB
- Number of GPUs: 4
- GPU Make: [Nvidia]

**Additional context**
Tried loading it manually via the following command,
```mergeable_ranks = load_tiktoken_bpe("llama3/Meta-Llama-3-8B/tokenizer.model")```
Gives the same `Error: Incorrect padding` error.

**Comment by IceClear** [comment]
I met the same problem. May I know is there any solutions?
