### ISSUE TITLE
The instructions to install Llama3 is horrible

### ISSUE THREAD

**Issue by Eyesun23** [meta-llama/llama#1131]
I followed the [steps](https://github.com/meta-llama/llama3) of getting access to the models; I received a link. But I am getting this error after I ran: 

`torchrun --nproc_per_node=1 example_chat_completion.py \
    --ckpt_dir Meta-Llama-3-8B-Instruct/ \
    --tokenizer_path Meta-Llama-3-8B-Instruct/tokenizer.model \
    --max_seq_len 512 --max_batch_size 6`

`WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
/opt/anaconda3/envs/llama3/bin/python: can't open file 'example_chat_completion.py': [Errno 2] No such file or directory
[2024-06-21 16:30:35,995] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 2) local_rank: 0 (pid: 97659) of binary: /opt/anaconda3/envs/llama3/bin/python
Traceback (most recent call last):
  File "/opt/anaconda3/envs/llama3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/llama3/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/opt/anaconda3/envs/llama3/lib/python3.8/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/opt/anaconda3/envs/llama3/lib/python3.8/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/opt/anaconda3/envs/llama3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/anaconda3/envs/llama3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-21_16:30:35
  host      : aysuns-mbp.attlocal.net
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 97659)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html`

**Comment by ENDGU** [comment]
I suspect the issue lies in the first line: ‘’/opt/anaconda3/envs/llama3/bin/python: can't open file 'example_chat_completion.py': [Errno 2] No such file or directory‘’，you can check if there is any problem with the file path when you run this command.
